source $fish_complete_path[-1]/ghi.fish #grab generated comp
complete -xc ghi -a '(set help (ghi --help); test (count $help) -gt 5; and for cmd in (string trim -- $help[5..-3]); set split (string split " " $cmd); echo -s $split[1] \t "$split[2..-1]"; end)'

# ghi
# Autogenerated from man page /usr/local/share/man/man1/ghi.1
#complete -c ghi -l version --description 'Prints the GHI version number.'
#complete -c ghi -l help --description 'Prints the synopsis and a list of commonly-used commands.'
#complete -c ghi -s p -l paginate --description 'Pipe all output into less if standard output is a terminal.'
#complete -c ghi -l no-pager --description 'Do not pipe output into a pager.'

